name: MongoDB Tools
description: A directory of GUIs, admin interfaces, and other tools for getting the most out of MongoDB, a popular open source document-oriented database.
markdown: redcarpet
highlighter: pygments
collections:
  tools:
    output: true
    permalink: /tool/:name/
gems:
  - jekyll-timeago
  - jekyll-sitemap
url: http://mongodb-tools.com
